ci: refactor ci and reuse vlab workflow for hlab as well
Signed-off-by: Sergei Lukianov <me@slukjanov.name>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -40,7 +40,7 @@ permissions:
   contents: read
 
 jobs:
-  test:
+  test-build:
     runs-on: lab
 
     steps:
@@ -70,6 +70,24 @@ jobs:
         run: |
           just --timestamp test
 
+      - name: Build all
+        run: |
+          just --timestamp build build-multi
+
+      - name: Go mod tidy
+        run: |
+          go mod tidy
+          go mod vendor
+
+      # Don't remove it! We shouldn't allow CI to pass if there are any changes not committed after running gen/lint/test
+      - name: Fail on dirty
+        run: |
+          if ! git status --short || [ -n "$(git status --porcelain)" ]; then
+            git --no-pager diff -- . :^vendor
+            echo "::error::Working directory is dirty. Please run 'just gen lint && go mod tidy && go mod vendor' and commit the changes."
+            exit 1
+          fi
+
       - name: Test diagram generation
         run: |
           mkdir -p test-diagrams
@@ -84,22 +102,8 @@ jobs:
       - name: Upload diagram artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: vlab-diagrams
+          name: test-build--diagrams
           path: test-diagrams
-
-      - name: Go mod tidy
-        run: |
-          go mod tidy
-          go mod vendor
-
-      # Don't remove it! We shouldn't allow CI to pass if there are any changes not committed after running gen/lint/test
-      - name: Fail on dirty
-        run: |
-          if ! git status --short || ! git diff --quiet; then
-            git --no-pager diff -- . :^vendor
-            echo "::error::Working directory is dirty. Please run 'just gen lint && go mod tidy && go mod vendor' and commit the changes."
-            exit 1
-          fi
 
       - name: Setup tmate session for debug
         if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
@@ -109,9 +113,12 @@ jobs:
           limit-access-to-actor: true
 
   # faster build installer without airgap using hosted runners and ghcr.io
-  build:
+  bundle:
     runs-on: ${{ matrix.os }}
     timeout-minutes: 15
+
+    needs:
+      - test-build
 
     strategy:
       matrix:
@@ -188,46 +195,15 @@ jobs:
         with:
           limit-access-to-actor: true
 
-  build-multi:
-    runs-on: lab
-    timeout-minutes: 15
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: stable
-          cache: true
-
-      - name: Setup Just
-        uses: extractions/setup-just@v3
-
-      - name: Build bins for all OS/ARCH
-        run: |
-          just --timestamp build-multi
-
-      - name: Setup tmate session for debug
-        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 30
-        with:
-          limit-access-to-actor: true
-
-  builds:
+  bundles:
     runs-on: ubuntu-latest
     needs:
-      - build
-      - build-multi
+      - bundle
     if: ${{ always() }}
 
     steps:
       - run: |
-          result="${{ needs.build.result }}"
+          result="${{ needs.bundle.result }}"
           if [[ $result == "success" || $result == "skipped" ]]; then
             exit 0
           else
@@ -235,16 +211,14 @@ jobs:
           fi
 
   vlab:
-    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-vlab') }}
-
     needs:
-      - test
-      - builds
+      - test-build
 
-    name: "vlab-${{ matrix.fabricmode == 'spine-leaf' && 'sl' || 'cc' }}-${{ matrix.gateway && 'gw-' || '' }}${{ matrix.includeonie && 'onie-' || '' }}${{ matrix.buildmode }}-${{ matrix.vpcmode }}"
+    name: "${{ matrix.hybrid && 'hlab' || 'vlab' }}-${{ matrix.fabricmode == 'spine-leaf' && 'sl' || 'cc' }}-${{ matrix.gateway && 'gw-' || '' }}${{ matrix.includeonie && 'onie-' || '' }}${{ matrix.buildmode }}-${{ matrix.vpcmode }}"
 
     uses: ./.github/workflows/run-vlab.yaml
     with:
+      skip: ${{ matrix.hybrid && contains(github.event.pull_request.labels.*.name, 'skip-hlab') || !matrix.hybrid && contains(github.event.pull_request.labels.*.name, 'skip-vlab') }}
       fabricatorref: ${{ github.ref }}
       fabricmode: ${{ matrix.fabricmode }}
       gateway: ${{ matrix.gateway }}
@@ -252,6 +226,7 @@ jobs:
       buildmode: ${{ matrix.buildmode }}
       vpcmode: ${{ matrix.vpcmode }}
       releasetest: ${{ inputs.run_release_test == true || contains(github.event.pull_request.labels.*.name, 'release-test') }}
+      hybrid: ${{ matrix.hybrid }}
 
     strategy:
       fail-fast: false
@@ -268,40 +243,52 @@ jobs:
           - manual
         vpcmode:
           - l2vni
+        hybrid:
+          - false
         include:
           - fabricmode: collapsed-core
             includeonie: false
             gateway: false
             buildmode: iso
             vpcmode: l2vni
+            hybrid: false
           - fabricmode: spine-leaf
             gateway: false
             includeonie: true
             buildmode: usb
             vpcmode: l2vni
+            hybrid: false
           - fabricmode: spine-leaf
             gateway: false
             includeonie: true
             buildmode: iso
             vpcmode: l2vni
+            hybrid: false
           - fabricmode: spine-leaf
             gateway: false
             includeonie: false
             buildmode: iso
             vpcmode: l3vni
+            hybrid: false
           - fabricmode: spine-leaf
             gateway: true
             includeonie: false
             buildmode: iso
             vpcmode: l2vni
+            hybrid: false
+          - fabricmode: spine-leaf
+            gateway: false
+            includeonie: false
+            buildmode: iso
+            vpcmode: l2vni
+            hybrid: true
 
   vlab-upgrade:
     if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-vlab') }}
 
     runs-on: vlab
     needs:
-      - test
-      - builds
+      - test-build
     timeout-minutes: 90
 
     strategy:
@@ -438,141 +425,11 @@ jobs:
             exit 1
           fi
 
-  hlab:
-    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-hlab') }}
-
-    runs-on: hlab
-    needs:
-      - test
-      - builds
-    timeout-minutes: 250
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - fabricmode: spine-leaf
-            includeonie: true
-            buildmode: iso
-
-    env:
-      slug: "${{ matrix.fabricmode }}-${{ matrix.includeonie }}-${{ matrix.buildmode }}"
-
-      # TODO enable for scheduled (github.event_name == 'schedule'), master and release branches?
-      run_release_test: ${{ inputs.run_release_test == true || contains(github.event.pull_request.labels.*.name, 'release-test') }}
-
-    steps:
-      - name: Runner host
-        run: |
-          echo "$KUBE_NODE"
-
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Checkout lab-ci repository
-        uses: actions/checkout@v4
-        with:
-          repository: githedgehog/lab-ci
-          path: "./lab-ci"
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: stable
-          cache: true
-
-      - name: Setup local registry
-        run: |
-          just --timestamp _localreg &
-
-      - name: Build hhfab
-        run: |
-          just --timestamp oci_repo=127.0.0.1:30000 oci=http push
-
-      - name: hhfab release test
-        env:
-          HHFAB_REG_REPO: 127.0.0.1:30000
-          HHFAB_VLAB_COLLECT: true
-        if: ${{ env.run_release_test == 'true' }}
-        run: |
-          source "./lab-ci/envs/$KUBE_NODE/source.sh"
-          bin/hhfab init -v --dev --include-onie=${{ matrix.includeonie }} -w "./lab-ci/envs/$KUBE_NODE/wiring.yaml"
-
-          # TODO: make controls restricted again when we figure out how to get NTP upstream working for isolated VMs
-          bin/hhfab vlab up -v --ready switch-reinstall --ready inspect --ready setup-vpcs --ready test-connectivity --ready release-test --ready exit --mode=${{ matrix.buildmode }} --controls-restricted=false
-          cat release-test.xml
-
-      - name: Upload Test Results
-        uses: actions/upload-artifact@v4
-        if: ${{ env.run_release_test == 'true' && !cancelled()}}
-        with:
-          name: Test Results for hlab--${{ env.slug }}
-          path: release-test.xml
-
-      - name: hhfab basic test-connectivity
-        env:
-          HHFAB_REG_REPO: 127.0.0.1:30000
-          HHFAB_VLAB_COLLECT: true
-        if: ${{ env.run_release_test != 'true' }}
-        run: |
-          source "./lab-ci/envs/$KUBE_NODE/source.sh"
-          bin/hhfab init -v --dev --include-onie=${{ matrix.includeonie }} -w "./lab-ci/envs/$KUBE_NODE/wiring.yaml"
-          bin/hhfab diagram -f mermaid
-
-          # TODO: make controls restricted again when we figure out how to get NTP upstream working for isolated VMs
-          bin/hhfab vlab up -v --ready switch-reinstall --ready inspect --ready setup-vpcs --ready test-connectivity --ready exit --mode=${{ matrix.buildmode }} --controls-restricted=false
-
-      - name: Upload show-tech artifacts
-        uses: actions/upload-artifact@v4
-        if: ${{ always() }}
-        with:
-          name: hlab--${{ env.slug }}--show-tech
-          path: show-tech-output
-
-      - name: Upload local registry logs
-        uses: actions/upload-artifact@v4
-        if: ${{ always() }}
-        with:
-          name: hlab--${{ env.slug }}--registry
-          path: .zot/log
-
-      - name: Upload mermaid diagram
-        uses: actions/upload-artifact@v4
-        if: ${{ always() }}
-        with:
-          name: hlab--${{ env.slug }}--mermaid
-          path: result/diagram.mmd
-
-      - name: Setup tmate session for debug
-        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 150
-        with:
-          limit-access-to-actor: true
-
-  hlabs:
-    runs-on: ubuntu-latest
-    needs:
-      - hlab
-    if: ${{ always() }}
-
-    steps:
-      - run: |
-          result="${{ needs.hlab.result }}"
-          if [[ $result == "success" || $result == "skipped" ]]; then
-            exit 0
-          else
-            exit 1
-          fi
-
   publish-test-results:
     if: inputs.run_release_test == true || contains(github.event.pull_request.labels.*.name, 'release-test')
     runs-on: lab
     needs:
-      - vlab
-      - hlab
+      - vlabs
 
     steps:
       - name: Download Artifacts
@@ -589,8 +446,8 @@ jobs:
     runs-on: lab
     if: startsWith(github.event.ref, 'refs/tags/v') && github.event_name == 'push'
     needs:
-      - build
-      - build-multi
+      - test-build
+      - bundle
       - vlab
       - vlab-upgrade
 
@@ -667,49 +524,6 @@ jobs:
           body: |
             This is an automated Pull Request created by GitHub Actions workflow,
             in the fabricator repository.
-
-      - name: Setup tmate session for debug
-        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 30
-        with:
-          limit-access-to-actor: true
-
-  publish-master:
-    runs-on: lab
-    if: github.event.ref == 'refs/heads/master' && github.event_name == 'push'
-    needs:
-      - build
-      - build-multi
-      - vlab
-      - vlab-upgrade
-
-    permissions:
-      contents: read
-      packages: write
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: stable
-          cache: true
-
-      - name: Login to ghcr.io
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Publish Images, Helm charts and Bins for master
-        run: |
-          just --timestamp oci_repo=ghcr.io version_extra=-master push push-multi
 
       - name: Setup tmate session for debug
         if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
